steps:
  # Step 1: Validate HTML files
  - name: 'ubuntu'
    args: ['bash', '-c', 'echo "Validating HTML files..." && ls -la *.html']
    id: 'validate'

  # Step 2: Create archive
  - name: 'ubuntu'
    args: ['tar', '-czf', 'website.tar.gz', 'index.html', 'deploy.sh']
    id: 'archive'

  # Step 3: Deploy to Staging
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Fetching SSH key..."
        gcloud secrets versions access latest --secret=cloud-build-ssh-key > id_rsa
        chmod 600 id_rsa

        echo "Deploying to staging..."
        scp -i id_rsa -o StrictHostKeyChecking=no index.html gafur@${_STAGING_VM_IP}:/tmp/
        scp -i id_rsa -o StrictHostKeyChecking=no deploy.sh gafur@${_STAGING_VM_IP}:/tmp/
        ssh -i id_rsa -o StrictHostKeyChecking=no gafur@${_STAGING_VM_IP} "bash /tmp/deploy.sh"
    id: deploy-staging

  # Step 4: Deploy to Production
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        echo "Fetching SSH key..."
        gcloud secrets versions access latest --secret=cloud-build-ssh-key > id_rsa
        chmod 600 id_rsa

        echo "Deploying to production..."
        scp -i id_rsa -o StrictHostKeyChecking=no index.html gafur@${_PROD_VM_IP}:/tmp/
        scp -i id_rsa -o StrictHostKeyChecking=no deploy.sh gafur@${_PROD_VM_IP}:/tmp/
        ssh -i id_rsa -o StrictHostKeyChecking=no gafur@${_PROD_VM_IP} "bash /tmp/deploy.sh"
    id: deploy-prod

# Define substitution variables (customize these per environment)
substitutions:
  _STAGING_VM_IP: '136.114.30.253'      # Replace with your staging VM IP
  _PROD_VM_IP: '34.67.75.90'         # Replace with your production VM IP
  _DEPLOY_USER: 'gafur'          # SSH username
  _APP_PATH: '/var/www/html'      # Apache web root

# Build timeout
timeout: '1800s'

# Options
options:
  # machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY