steps:
  # Step 1: Validate HTML files
  - name: 'ubuntu'
    args: ['bash', '-c', 'echo "Validating HTML files..." && ls -la *.html']
    id: 'validate'

  # Step 2: Copy files to archive
  - name: 'ubuntu'
    args: ['tar', '-czf', 'website.tar.gz', 'index.html', 'deploy.sh', '*.html']
    id: 'archive'

  # Step 3: Deploy to Staging VM
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /workspace/id_rsa
        echo "Deploying to staging..."
        scp -i /workspace/id_rsa -o StrictHostKeyChecking=no -r index.html deploy@${_STAGING_VM_IP}:/tmp/
        scp -i /workspace/id_rsa -o StrictHostKeyChecking=no deploy.sh deploy@${_STAGING_VM_IP}:/tmp/
        ssh -i /workspace/id_rsa -o StrictHostKeyChecking=no deploy@${_STAGING_VM_IP} 'bash /tmp/deploy.sh'
    id: 'deploy-staging'

  # Step 4: Deploy to Production VM
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        chmod 600 /workspace/id_rsa
        echo "Deploying to production..."
        scp -i /workspace/id_rsa -o StrictHostKeyChecking=no -r index.html deploy@${_PROD_VM_IP}:/tmp/
        scp -i /workspace/id_rsa -o StrictHostKeyChecking=no deploy.sh deploy@${_PROD_VM_IP}:/tmp/
        ssh -i /workspace/id_rsa -o StrictHostKeyChecking=no deploy@${_PROD_VM_IP} 'bash /tmp/deploy.sh'
    id: 'deploy-prod'

# Define substitution variables (customize these per environment)
substitutions:
  _STAGING_VM_IP: '34.68.88.54'      # Replace with your staging VM IP
  _PROD_VM_IP: '34.67.75.90'         # Replace with your production VM IP
  _DEPLOY_USER: 'deploy'          # SSH username
  _APP_PATH: '/var/www/html'      # Apache web root

# Build timeout
timeout: '1800s'

# Options
options:
  # machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY